### ISSUE TITLE
Move Setting Up Your Environment to autogenerate

### ISSUE THREAD

**Issue by pete0emerson** [gruntwork-io/docs#109]

**Comment by pete0emerson** [comment]
See https://github.com/gruntwork-io/docs/pull/103#discussion_r770153713

**Comment by brikis98** [comment]
@pete0emerson Please add context / description / acceptance criteria to this one.

**Comment by ebeneliason** [comment]
I believe this was in reference to [this comment](https://github.com/gruntwork-io/docs/pull/103#discussion_r770153713).

> Two thoughts here…
> 
> We might not need to list all of these explicitly if we leverage autogenerate as some other sections do. (That does have some other implications for ordering, though.)
> It looks like your editor isn't set up to enforce our prettier config, which could make future diffs messy.
> We should think about how we want to standardize on both of these fronts. @eak12913 @oredavids Your technical insights here would be helpful.

As fortune would have it, we've since flip-flopped on the best-practice, and now believe that explicit sidebar files provide better legibility and an easier maintenance story. I'll close this issue accordingly.
