### ISSUE TITLE
Re-running `yarn start` with un-committed changes removes those changes

### ISSUE THREAD

**Issue by josh-padnick** [gruntwork-io/docs#890]
Here's how to reproduce:

1. Run `yarn start`
2. Update a doc. The changes are reflected in the locally running version as expected.
3. Do _not_ commit those changes to git.
4. CTRL-C
5. Re-run `yarn start`

The changes from (2) now disappear. This bit me hard when I restarted `yarn start` without committing my changes. I was only able to recover them from my IDE's memory.

**Comment by eak12913** [comment]
Where did you make changes? Recall that the 'docs-sourcer' runs on each save and also on each restart. If you changed a file in the /docs/.... folder instead of changing it in _docs-sources/.... then it would get blown away when the restart happened because you would have updated a "generated" version of the file rather than updating its source.

**Comment by josh-padnick** [comment]
Ah...that was the issue. Uh oh, I'm now realizing I need to check my past PRs to make sure I didn't commit changes only to generated files. Maybe the real change here is just updating the docs to clarify in which folder to write new docs.
